# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
  # Pods for Weather
pod 'SwiftyKeychainKit', '1.0.0-beta.2'
end
